---
# Step One — Set Up New Document Root Directories
- file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    recurse: yes
    mode: 0755
  become: true
  with_items:
  - ["/var/www/example.com/html", "/var/www/test.com/html"]

# Step Two — Create Sample Pages for Each Site
- copy:
    src: roles/Nginx/files/configurations/service/test_index.html
    dest: /var/www/test.com/html/index.html
  become: true

- copy:
    src: roles/Nginx/files/configurations/service/example_index.html 
    dest: /var/www/example.com/html/index.html 
  become: true

# Configure Nginx to Use Custom Error Pages
- copy:
    src: "{{ item }}"
    dest: /usr/share/nginx/html
  become: true
  with_items:
  - ["roles/Nginx/files/configurations/service/custom_404.html", "roles/Nginx/files/configurations/service/custom_50x.html"]

# Step Three — Create Server Block Files for Each Domain
- copy:
    src: roles/Nginx/files/configurations/service/example.com
    dest: /etc/nginx/sites-available/example.com
  become: true

- copy:
    src: roles/Nginx/files/configurations/service/test.com        
    dest: /etc/nginx/sites-available/test.com  
  become: true

# Step Four — Enable your Server Blocks and Restart Nginx
- shell: ln -s /etc/nginx/sites-available/example.com /etc/nginx/sites-enabled/
  become: true

- shell: ln -s /etc/nginx/sites-available/test.com /etc/nginx/sites-enabled/
  become: true

- shell: rm /etc/nginx/sites-enabled/default
  become: true

- copy:
    src: roles/Nginx/files/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
  become: true

- name: Restart nginx service
  systemd: state=restarted name=nginx
  become: true
