---
- name: Install python-docker on Debian based distribution
  apt:
    name: python-docker
    update_cache: yes
- name: Log into DockerHub
  docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
    email: "{{ docker_email }}"
- name: Pull an image
  docker_image:
    name: 5097104/hello-world-v.1.1

