- name: Configure CI server
  hosts: localhost
  connection: local
  sudo: True
  roles:
    - geerlingguy.jenkins
  tasks:
    - include_tasks: roles/geerlingguy.jenkins/tasks/cwt_configuration.yml
    - include_tasks: ssh-known-hosts.yml
