---
- name: Create docker_cwt directory
  file:
    path: /var/lib/jenkins/jobs/docker_cwt
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755

- name: Set the docker_cwt job configuration
  template:
    src: roles/CWT/template/jenkins_docker_config.xml
    dest: /var/lib/jenkins/jobs/docker_cwt/config.xml
    owner: jenkins
    group: jenkins
    mode: 0755

- name: Set Ansible tool configuration
  template:
    src: roles/CWT/template/global_tool_jenkins_configuration.xml
    dest: /var/lib/jenkins/org.jenkinsci.plugins.ansible.AnsibleInstallation.xml
    owner: jenkins
    group: jenkins
    mode: 0755

- name: Copy the Ansible plugin
  copy:
    src: roles/CWT/files/ansible.jpi
    dest: /var/lib/jenkins/plugins/ansible.jpi

- name: Immediately restart Jenkins on init config changes
  service: name=jenkins state=restarted

