- name: Create EC2 instances
  ec2:
   key_name: "{{ ec2_keypair }}"
   instance_type: "{{ ec2_instance_type }}"
   image: "{{ ec2_image }}"
   region: "{{ ec2_region }}"
   group: "{{ ec2_security_group }}"
   wait: yes
  register: ec2_instances

- stat:
    path: "{{ instance_id_file }}"
  register: p

- name: Create a new instance id file
  file:
    path: "{{ instance_id_file }}"
    mode: 0777
    state: '{{ "absent" if p.stat.exists else "touch" }}'
  delegate_to: localhost

- name: Write to a file
  shell: echo "{{ ec2_instances.instance_ids[0] }}" >> "{{ instance_id_file }}"
  delegate_to: localhost


