- name: Create EC2 instances
  ec2:
   key_name: "{{ ec2_keypair }}"
   instance_type: "{{ ec2_instance_type }}"
   image: "{{ ec2_image }}"
   region: "{{ ec2_region }}"
   group: "{{ ec2_security_group }}"
   wait: yes
   instance_tags:
     application: webservercontrol2
   exact_count: 1
   count_tag:
     application: webservercontrol2
  register: ec2_instances

- name: Print ec2_instances
  debug:
    msg: "{{ ec2_instances.instance_ids[0] }}"

- name: Create file
  file:
    dest: "/home/{{ lookup('env','USER') }}/instance.txt"
    state: touch
    mode: 0777
  delegate_to: localhost

- name: Write to a file
  shell: echo "{{ ec2_instances.instance_ids[0] }}" >> "/home/{{ lookup('env','USER') }}/instance.txt"
  delegate_to: localhost
