---
- name: Debug OS
  debug:
    msg: "os: {{ ansible_os_family }}"

- name: Configuring Windows
  block:
    # Install dependencies
    - include_tasks: install_dependencies.yml
    # Configure microservice
    - include_tasks: microservice.yml
  when: ( ansible_os_family == "windows" )
