---
- name: Create microservice folder in Windows
  win_file:
    path: C:\microservice
    state: directory

- name: Copy microservice on Windows
  win_copy:
    src: "{{ item }}"
    dest: C:\\microservice\\
  with_items:
    - /etc/ansible/roles/windows/files/microservice.py
    - /etc/ansible/roles/windows/files/counter.dat

- name: Run microservice
  win_command: python C:\microservice\microservice.py

